version: '3.8'

services:
    mysql:
        container_name: telegram-mermaid-mysql
        image: mysql
        volumes:
            - mysql-volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mermaid
            MYSQL_USER: mermaid
            MYSQL_PASSWORD: mermaid
        ports:
            - "3306:3306"

volumes:
    mysql-volume:
        name: telegram-mermaid-mysql-volume
